name: Testing

on: push                                        # запускается на любом пуше

jobs:                                           # набор шагов, которые выполняются на одной виртуальной машине
  build:
    runs-on: ubuntu-latest                      # тип виртуальной машины
    steps:                                      # начало списка шагов, которые будут выполняться по порядку
      - uses: actions/checkout@v4               # клонируем репозиторий

      - name: Установить Python                 # установка нужной версии Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Установить зависимости            # устанавливаем нужные зависимости
        run: |                                  # последовательность команд для установки
          python -m pip install --upgrade pip   # обновление pip до актуальной версии
          pip install -r requirements.txt       # рекомендуем устанавливать зависимости через requirements.txt
          pip install pytest                    # если нет в requirements.txt, установим отдельно pytest
          pip install hypothesis                 # гипотеза тоже ставится отдельным пакетом

      - name: Выполнить тесты                   # основной шаг для запуска тестов
        env:                                    # добавляем переменные окружения
          PYTHONPATH: ${{ github.workspace }}   # задаем путь для импорта модулей внутри рабочей области
        run: |
          pytest tests/ -v
